#!/bin/sh
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

INSTALL_DIR="/usr/share/roundcube"
ROUNDCUBE_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-roundcube-site.conf"

if [ -e "${ROUNDCUBE_SITE_CONF}" ]; then
    rm ${ROUNDCUBE_SITE_CONF}
fi

if [ "$(omv_config_get "//services/roundcube/enable")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${ROUNDCUBE_SITE_CONF}"
location /webmail/ {
    alias ${INSTALL_DIR};
    index index.php;
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm-openmediavault-roundcube.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
    location ~ ^/roundcube/(bin|SQL|config|logs|\.ht)/ {
        deny all;
    }
    location = /roundcube/favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /roundcube/robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location /roundcube/ {
        try_files \$uri \$uri/ /roundcube/index.php?\$args;
    }
    location ~ /roundcube/\. {
        deny all;
    }
    location ~* /roundcube/\.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}
EOF

exit 0
