#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

ROUNDCUBE_SITE_ENABLED_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-roundcube-site.conf"

if [ -e "${ROUNDCUBE_SITE_ENABLED_CONF}" ]; then
    rm ${ROUNDCUBE_SITE_ENABLED_CONF}
fi

if [ "$(omv_config_get "//services/roundcube/enable")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${ROUNDCUBE_SITE_ENABLED_CONF}"
location /webmail/ {
    alias /var/www/roundcube/;
    index index.php;
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm-openmediavault-webgui.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ ^/(bin|SQL|config|logs)/ {
        deny all;
    }

    location ~ /\.ht {
        deny all;
    }
}
EOF

exit 0
