#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Setup from: http://trac.roundcube.net/wiki/Howto_Install

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="roundcube"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    configure)

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            DES_KEY=$(</dev/urandom tr -dc "A-Za-z0-9!@#%^*" | head -c24)
            
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "default_host" ""
            omv_config_add_element "${SERVICE_XPATH}" "smtp_server" ""
            omv_config_add_element "${SERVICE_XPATH}" "smtp_port" ""
            omv_config_add_element "${SERVICE_XPATH}" "smtp_user" ""
            omv_config_add_element "${SERVICE_XPATH}" "smtp_pass" ""
            omv_config_add_element "${SERVICE_XPATH}" "product_name" "Roundcube Webmail"
            omv_config_add_element "${SERVICE_XPATH}" "des_key" "${DES_KEY}"
            omv_config_add_element "${SERVICE_XPATH}" "db_host" "localhost"
            omv_config_add_element "${SERVICE_XPATH}" "db_user" "roundcube"
            omv_config_add_element "${SERVICE_XPATH}" "db_pass" "openmediavault"
            omv_config_add_element "${SERVICE_XPATH}" "db_name" "roundcube"
        fi    
        
        omv-mkconf roundcube install
        
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
